### ISSUE TITLE
Using system Eigen instead of local one

### ISSUE THREAD

**Issue by j8asic** [pmp-library/pmp-library#106]
PMP is forcing to use local Eigen lib `set(EIGEN_SOURCE_DIR "external/eigen")`

In complex/multiple projects that wish to use single and system-wide Eigen, it would be preferable that the `EIGEN_SOURCE_DIR` is set to `"external/eigen"` only if global is not successfully found using `find_package (Eigen3 NO_MODULE)`

**Comment by dsieger** [comment]
Yes, for the moment this is a conscious decision. See also PR #86. I'm not really keen on supporting older versions of Eigen.

However, this is not set in stone :-)

**Comment by ramcdona** [comment]
Consider this a +1 for this option.

Eigen is a bit 'easier' for this than some other libraries.  Since it is header only, you're only taking on a build-time dependency, not a runtime one.

You can certainly put requirements on the Eigen version via the CMake FindXXX command.  You are also under no obligation to test compatibility, performance, or anything else with a user-supplied library (vs. the bundled version).

My program makes extensive use of Eigen, Eigen is already integrated into my build system (as a bundled component that can optionally be replaced by a system-provided one).  I would like to be assured that I can pass data between my program and PMP without having to worry about different versions of Eigen or having to write a bunch of glue code to pass between Eigen and Eigen.

I am certainly not going to adopt the PMP bundled version of Eigen throughout my program -- I still at the stage of evaluating PMP.

Being forced to use the bundled Eigen is currently a reason to not use PMP.

**Comment by dsieger** [comment]
Fixed in 2382778c560e7bed5d5b01a31a3b75af4c054649
