### ISSUE TITLE
Fastest way to add vertices, faces, vertex colors, uvs

### ISSUE THREAD

**Issue by thomastong** [pmp-library/pmp-library#126]
Hi, 

We have existing file loaders and which popular our own mesh structure that contains points, faces, in linear vectors.  Rather than adding vertex's one at a time, is there a way for us to populate vertexes and triangles fast way, via a mem copy mechanism or call a function to pass in arrays of values?

We load in fairly large datasets at millions of points / faces.

**Comment by thomastong** [comment]
Also how would you manually add vertex colors and UV's if you're going through the OBJ loader?

**Comment by dsieger** [comment]
Short answer to your first question: There currently is no way to bypass the `add_face/vertex` functions since those take care of building up the actual internal data structure.

Unfortunately, our OBJ reader currently does not support vertex colors and only supports texture coordinates per halfedge. Going through the OFF reader would be an alternative, which supports both.

**Comment by thomastong** [comment]
Thanks that answers my question!
