### ISSUE TITLE
VCPKG integration

### ISSUE THREAD

**Issue by cdcseacave** [pmp-library/pmp-library#13]
[vcpkg](https://github.com/Microsoft/vcpkg) is a relatively new library managing system, primarily developed for Windows, but running on Linux and Mac too. I find it extremely useful and easy to use, and I'm sure many other too. Are you considering adding your library to `vcpkg` in order to make it easy to access?

**Comment by dsieger** [comment]
Hi,

I was recently investigating both vcpkg as well as conan as potential package management solutions, especially since this would give us a more proper way for handling third-party dependencies (instead of using git submodules). However, I've yet to come to a conclusion. My main concern right now is ease of use / accessibility. Our current setup procedure is rather standard and straightforward (git clone and build), so I'm hesitating to add not so wide-spread tools into the mix.

Regards,
Daniel
