### ISSUE TITLE
CMake option to disable warning as errors

### ISSUE THREAD

**Issue by sunbubble** [pmp-library/pmp-library#153]
Using `-Werror` is a great practice for local development. Unfortunately, for external consumers of the library, it often causes the compilation of pmp to fail whenever a newer compiler version is used which introduces new types of warnings.

Could we add a CMake option to disable warnings as errors that a consumer of this library could use, without having to change the source code?

Thanks very much in advance.

line in question: https://github.com/pmp-library/pmp-library/blob/eb4cd52b820bc82ba9cfe2e0a73f5924e55e999a/CMakeLists.txt#L110

**Comment by dsieger** [comment]
Of course, you're also welcome to submit a PR fixing the warnings you get! ;-)

Note that the current solution in [d4cfb00](https://github.com/pmp-library/pmp-library/commit/d4cfb00b34bd0f512858e2a0367e6b1bc4710185) might be more of a workaround. This issue is a good reminder that our CMake infrastructure needs some work. Overriding global compile options using `CMAKE_CXX_FLAGS` is certainly not the way to go.

**Comment by sunbubble** [comment]
The issues have already been fixed in the main branch. We had a bunch of unused variable warnings in the v2.0.1 release
