### ISSUE TITLE
Boolean difference/intersection

### ISSUE THREAD

**Issue by petrasvestartas** [pmp-library/pmp-library#56]
Hi,

Does this library has mesh boolean methods such as difference/intesection?

**Comment by dsieger** [comment]
Hi,

Sorry, we currently don't have methods for that. I'm marking this as a potential enhancement. However, given the complexity of such functionality, I don't expect someone to implement this soon. Any volunteers?

Thanks,
Daniel

**Comment by petrasvestartas** [comment]
Besides monsters like CGAL or libigl, are there any robust C++ libraries for Booleans? I know that Cork and latest 2020 sigraph paper do not work well in all cases... I understand that Booleans are not easy, but why most mesh processing libraries do not have such methods even it is described in books by such famous authors as you?

**Comment by dsieger** [comment]
There is [GTS](http://gts.sourceforge.net/). In never tried their Boolean implementation, so I'm not sure how robust this is. I've had mixed experiences with that library in the past.

[MeshMixer](https://www.meshmixer.com) from Autodesk has Boolean operations as well, but I don't think this is available as a library.

As for why we don't have such functionality: It's a tough problem, and we did not yet have a real use case for it. We had requests for it in the past, that's why I'm keeping it open as potential enhancement.

Hope this helps,
Daniel

**Comment by petrasvestartas** [comment]
Thanks for the reference.
Hope somebody will tackle this hard problem in PMP as well.
