### ISSUE TITLE
using non-gpl eigen only

### ISSUE THREAD

**Issue by malytomas** [pmp-library/pmp-library#63]
Hi,

All (l)gpl licensed code is strictly forbidden in our company and pmp version 1.2.1 can be compiled with EIGEN_MPL2_ONLY, which ensures that no (l)gpl code from eigen is used.

However, latest master 6deb83456115275aea004be43b0c934d53097061 seems to be unable to build with that macro defined.

I would like to ask what to expect in future: will pmp require (l)gpl licensed code or will this be fixed?

Thanks.

**Comment by dsieger** [comment]
Hi @malytomas ,

Thanks for bringing up this issue. Seems to be an upstream Eigen issue. Using the Eigen version from 1.2.1 with our current master shows no problem. The same is true for current Eigen master and 3.4.0-rc1.

The SimplicialLDLT  solver we are using was excluded due to [this bug report](https://gitlab.com/libeigen/eigen/-/issues/1392).
This was later removed after re-licensing the code, see [this commit](https://gitlab.com/libeigen/eigen/-/commit/0318fc7f44a3440995494c835b859a1dabe0e4c8).

I will upgrade to the latest Eigen version before our next release, so this should not be an issue.

In general, I'll try to keep PMP as (L)GPL-free as possible.

Thanks,
Daniel
