### ISSUE TITLE
Test Mesh Validity

### ISSUE THREAD

**Issue by petrasvestartas** [pmp-library/pmp-library#74]
Hi,

I would like to ask if there is a method to test mesh validity and giving some hints why the mesh is not valid? Maybe you have some common procedure to test a given mesh?

I.e. mesh has no vertex nomals, mesh has coincident faces, vertices, faces indices are the same and other pissible errors.

**Comment by dsieger** [comment]
Sorry, but we currently don't have a simple method to analyze and check mesh validity.

One potential source of error could be an experimental feature that we have enabled on the master branch: We currently duplicate non-manifold faces so that we can also load non-manifold meshes. You could add a simple debug message to `SurfaceMeshIO::add_face()` to see if that's the case for you.

Note that this feature is experimental, and we might decide to remove it exactly because it can lead to this kind of confusion / errors.
