### ISSUE TITLE
Geodesic Distance

### ISSUE THREAD

**Issue by petrasvestartas** [pmp-library/pmp-library#78]
I honestly cannot stop learning from this awesome library! First sorry from too many questions.
Now I am following Geodesic distance test  files which works very well.

I have two questions:
1) How you would compute geodesic distance form a curve or a line? Would you use multiple points?
2) Is there any method to split mesh into series of stripes (right image) like the one I did below? I did this using my old code in C# language that takes 2.4 sec which is very slow:

![Geodesics](https://user-images.githubusercontent.com/18013985/127773791-0211dd89-17ff-4ea9-8d81-f7a62b2e5148.png)

**Comment by mbotsch** [comment]
1. We do not support geodesic distances from lines or edges. You can approximate this distance by using all vertices of the curve/edge as seeds.
2. If you want to cut the mesh into disconnected strips, the answer is no. If you want the "striped" appearance, you can simply load a texture with a discrete color ramp (instead of a smooth blend). I'm attaching an example of a "discrete color map" and the resulting geodesic visualization.

```
SurfaceGeodesic geodist(mesh);
geodist.compute(seed);
geodist.distance_to_texture_coordinates();
mesh.load_texture("color-ramp.png");
```
![color-ramp](https://user-images.githubusercontent.com/31275467/128024675-1408aae9-e694-4716-9eb8-1090e5179f43.png)
![Screenshot 2021-08-03 at 15 33 05](https://user-images.githubusercontent.com/31275467/128024766-72e63769-25b7-4f85-9b80-30a1f1f2c5ae.png)
