### ISSUE TITLE
uniform_remeshing() crashes in VertexAroundFaceCirculator()

### ISSUE THREAD

**Issue by cdcseacave** [pmp-library/pmp-library#90]
**Describe the bug**
Often the pmp::SurfaceRemeshing::uniform_remeshing() crashes in the same place: VertexAroundFaceCirculator().

**To Reproduce**
Please find attached a sample mesh. It is manifold, and clean of small components (as least 3x larger than the desired face length). The following code crashes:
```
		pmp::SurfaceMesh mesh;
		// load mesh
		pmp::SurfaceRemeshing remesh(mesh);
		remesh.uniform_remeshing(0.0410);
```

![image](https://user-images.githubusercontent.com/2802670/139417021-22f5bd91-a3a1-4dbf-bbcf-8a05bad3321c.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Compiler: VC++ 2019
 - Build type: Debug and Release

Sample mesh:
[mesh_clean.zip](https://github.com/pmp-library/pmp-library/files/7441046/mesh_clean.zip)

**Comment by dsieger** [comment]
Hi,

Just did a quick check, and the mesh looks anything but clean.
 
There are boundary edges all over the place which are likely to cause trouble:

<img width="414" alt="Screenshot 2021-11-16 at 22 31 40" src="https://user-images.githubusercontent.com/6951585/142079798-0732fb57-bef5-4eaf-a591-1f00f288cbcc.png">

Then the mesh contains so much noise and close to zero volume components with degenerate elements:

<img width="622" alt="Screenshot 2021-11-16 at 23 57 10" src="https://user-images.githubusercontent.com/6951585/142080210-29df00c3-ac33-4222-aa82-6987ed33af0f.png">

I honestly doubt there's any hope to get this remeshed with our algorithm without serious cleanup and pre-processing. Sorry, but this is beyond the scope of what we can currently offer.

**Comment by cdcseacave** [comment]
Thx for looking into this. By clean I meant manifold, with no degenerate faces, etc. From the description of the algorithm: `The algorithm implemented here performs incremental remeshing based on edge collapse, split, flip, and tangential relaxation.` it sounds that it should work on my mesh. Can you pls at least add some minimum requirements the mesh should fulfill so that other like me do not waste their time trying your library?

And on the other hand, if the algorithm does not handle meshes with boundaries and non-uniform faces, that sounds like the input should be an isotropic mesh, what the remesh algorithm is expected to provide in the first place. So what does your algorithm do then?

**Comment by dsieger** [comment]
First of all, I find the tone of your reply to be borderline aggressive. We are developing this library in our precious spare time and make it available for free. I've got no intention whatsoever to spend my time in disrespectful discussions. So, please keep it down a bit, OK?

On topic: Of course the algorithm does what's in the description, including handling boundaries and non-uniform triangulations. However, that does not mean that it is robust against all sorts of degenerate input configurations, and this is exactly what's happening here: The tangential relaxation produces some NaN vertices which in turn lead to trouble in subsequent steps.

There are some ways we could make this more robust, and your mesh obviously is an excellent stress test. Thanks for sharing! We'll check if there's a feasible way to improve the robustness of our algorithm.

However, experience tells me that even if you succeed remeshing this particular mesh, the output is likely to be dissatisfactory, simply because the input is already so close to being degenerate.

Take care,
Daniel

**Comment by dsieger** [comment]
This is actually related to #89, re-opening.

**Comment by dsieger** [comment]
I put some improvements into a feature branch: [remeshing-robustness](/pmp-library/pmp-library/tree/remeshing-robustness). With those changes I'm able to remesh the model you provided. If you have other problematic models you can share, I'd be glad to have a look.

**Comment by cdcseacave** [comment]
That is great news. I have tons of such meshes. In fact I was able to remesh only one mesh till now: the mesh of a planar surface. I'll try your branch in the following days. Thank you!

**Comment by cdcseacave** [comment]
I tried on a mesh of 6M faces, but it run for 14h without finishing. It did not crash, but it seems slower. Any suggestions how to tackle this problem? One though is to use mesh simplification to get the mesh close to the desired edge length, and then run remeshing just to "fair" the mesh triangles. Can you suggest a simple and fast heuristic to compute the decimation factor from the desired average edge length? Or a completely different approach?

**Comment by dsieger** [comment]
Performance on well-behaved meshes is identical. If your mesh contains lots of degeneracies it will take some more time to perform fallback computations. No free lunch.

If the meshes you are dealing with have similar quality as the one you shared, I doubt there will be a push-button solution.

@MarcoAttene's [MeshFix](https://github.com/MarcoAttene/MeshFix-V2.1) might be worth checking out for mesh repair and pre-processing.
